supertokens/supertokens-python

- CHANGELOG.md
- frontendDriverInterfaceSupported.json
- supertokens_python/recipe/thirdparty/api/implementation.py
- supertokens_python/recipe/thirdparty/api/signinup.py
- supertokens_python/recipe/thirdparty/interfaces.py
- supertokens_python/recipe/thirdpartyemailpassword/api/implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/api/thirdparty_api_implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/interfaces.py
Adds authCodeResponse to third party APIs
-   https://github.com/supertokens/frontend-driver-interface/issues/24
-   [x] Had run `make lint`
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is …
> adds changes as per new FDI spec

- supertokens_python/recipe/thirdpartyemailpassword/api/implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/implementation.py
- tests/test_config.py
-   #47 
-   [ ] Had run `make lint`
-   If no such branch exists, then create one from the latest released …
> closes #47

- CHANGELOG.md
- supertokens_python/supertokens.py
- tests/auth-react/fastapi/app.py
- tests/auth-react/flask/app.py
Allow user to handle general exceptions.
https://github.com/supertokens/supertokens-python/issues/13
I ran all the tests. All the tests have passed. 
-   [ ] Had run `make lint`
-   [ ] Issue this PR …
> Allow user to handle general exceptions

- CHANGELOG.md
- coreDriverInterfaceSupported.json
- setup.py
- supertokens_python/asyncio/__init__.py
- supertokens_python/constants.py
- supertokens_python/supertokens.py
- supertokens_python/syncio/__init__.py
- tests/emailpassword/test_signin.py
Delete user function
-   https://github.com/supertokens/supertokens-core/issues/341
TODO
Added a section about delete user
-   [x] Had run `make lint`
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose …
> adds function for delete_user

- .circleci/setupAndTestWithAuthReact.sh
- .circleci/setupAndTestWithAuthReactWithDjango.sh
- .circleci/setupAndTestWithAuthReactWithFlask.sh
- tests/auth-react/django3x/mysite/settings.py
- tests/auth-react/django3x/polls/views.py
- tests/auth-react/fastapi/app.py
- tests/auth-react/flask/app.py
- adds auth0 as a custom provider to django, fastapi and flask for tests
-   https://github.com/supertokens/for-zenhub/issues/58
-   In …
> Adds auth0 sp test

- CHANGELOG.md
- setup.py
- supertokens_python/__init__.py
- supertokens_python/constants.py
- supertokens_python/recipe/passwordless/__init__.py
- supertokens_python/recipe/passwordless/recipe.py
- supertokens_python/recipe/passwordless/utils.py
- supertokens_python/recipe/session/__init__.py
- supertokens_python/recipe/session/recipe.py
- supertokens_python/recipe/session/utils.py
- supertokens_python/recipe/thirdparty/interfaces.py
- tests/frontendIntegration/django2x/polls/views.py
Bug fixes in Literal import which caused issues when using the sdk with python version 3.7
> bug fixes for python 3.7 use case

- CHANGELOG.md
- supertokens_python/recipe/thirdpartyemailpassword/api/emailpassword_api_impementation.py
- supertokens_python/recipe/thirdpartyemailpassword/api/implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/asyncio/__init__.py
- supertokens_python/recipe/thirdpartyemailpassword/interfaces.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/email_password_recipe_implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/third_party_recipe_implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/syncio/__init__.py
Makes tpep function names more friendly
-   https://github.com/supertokens/supertokens-node/issues/219
-   [x] Had run `make lint`
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than …
> refactor!: renames functions in tpep

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/supertokens.py
- tests/test_pagination.py
Fix pagination in get_users() function
Fixes https://github.com/supertokens/supertokens-python/issues/95
Included with the PR
Not required
-   [ ] If added a new recipe that has a User type with extra info, then be sure to change the User type in supertokens_python/types.py
-   [ ] If have added a new web framework, update the `supertokens_python/utils.py` file to include that …
> fix: Fix get_users pagination

- examples/with-fastapi/with-thirdpartyemailpassword/main.py
- examples/with-flask/with-thirdpartyemailpassword/app.py
- supertokens_python/logger.py
- supertokens_python/recipe/emailpassword/api/email_exists.py
- supertokens_python/recipe/emailpassword/api/generate_password_reset_token.py
- supertokens_python/recipe/emailpassword/api/password_reset.py
- supertokens_python/recipe/emailpassword/api/signin.py
- supertokens_python/recipe/emailpassword/api/signup.py
- supertokens_python/recipe/emailverification/api/email_verify.py
- supertokens_python/recipe/emailverification/api/generate_email_verify_token.py
- supertokens_python/recipe/jwt/api/jwks_get.py
- supertokens_python/recipe/openid/api/open_id_discovery_configuration_get.py
- supertokens_python/recipe/passwordless/api/consume_code.py
- supertokens_python/recipe/passwordless/api/create_code.py
- supertokens_python/recipe/passwordless/api/email_exists.py
- supertokens_python/recipe/passwordless/api/phone_number_exists.py
- supertokens_python/recipe/passwordless/api/resend_code.py
- supertokens_python/recipe/session/api/refresh.py
- supertokens_python/recipe/session/api/signout.py
- supertokens_python/recipe/session/recipe.py
- supertokens_python/recipe/session/recipe_implementation.py
- supertokens_python/recipe/session/session_functions.py
- supertokens_python/recipe/session/utils.py
- supertokens_python/recipe/thirdparty/api/authorisation_url.py
- supertokens_python/recipe/thirdparty/api/signinup.py
- supertokens_python/supertokens.py
- supertokens_python/utils.py
- tests/test_logger.py
Adds logging messages.
-   https://github.com/supertokens/for-zenhub/issues/111
> feat: Log messages for debugging

- CHANGELOG.md
- supertokens_python/supertokens.py
Fix asyncio related errors when telemetry is enabled for FastAPI
Fixes https://github.com/supertokens/supertokens-core/issues/421
-   In …
> fix: Fix asyncio related errors when telemetry is enabled for FastAPI

- CHANGELOG.md
- examples/with-fastapi/with-thirdpartyemailpassword/main.py
- examples/with-flask/with-thirdpartyemailpassword/app.py
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/emailverification/utils.py
- bug fix in `default_create_and_send_custom_email` function for email verification recipe
- removing the code that set `SUPERTOKENS_ENV` env to `testing` for example apps
> fix: emailverification default send email bug fix

- .github/helpers/.gitignore
- .github/helpers/package.json
- .github/workflows/tests-pass-check-pr.yml
- .github/workflows/tests.yml
- CHANGELOG.md
Adds github action for running tests manually and making sure that PRs are created with tests passing
-   [ ] Making sure that check PR test workflow is working
> ci: Adds github action for running tests

- CHANGELOG.md
- dev-requirements.txt
Upgrade pyright version in dev-requirements.txt to fix errors thrown by `make check-lint`
-   [ ] Had …
> feat: Upgrade pyright version in dev-requirements.txt

- supertokens_python/ingredients/emaildelivery/service/smtp.py
- supertokens_python/recipe/emailpassword/api/implementation.py
- supertokens_python/recipe/emailpassword/emaildelivery/__init__.py
- supertokens_python/recipe/emailpassword/emaildelivery/service/smtp/__init__.py
- supertokens_python/recipe/emailpassword/emaildelivery/service/smtp/email_verification_implementation.py
- supertokens_python/recipe/emailpassword/emaildelivery/service/smtp/implementation.py
- supertokens_python/recipe/emailpassword/emaildelivery/service/smtp/password_reset_implementation.py
- supertokens_python/recipe/emailpassword/emaildelivery/service/smtp/service_implementation/__init__.py
- supertokens_python/recipe/emailpassword/emaildelivery/service/smtp/service_implementation/email_verification_implementation.py
- supertokens_python/recipe/emailpassword/utils.py
- supertokens_python/recipe/emailverification/emaildelivery/service/smtp/__init__.py
- supertokens_python/recipe/emailverification/emaildelivery/service/smtp/email_verify.py
- supertokens_python/recipe/emailverification/emaildelivery/service/smtp/implementation.py
- supertokens_python/recipe/emailverification/interfaces.py
- tests/test_email.py
Add SMTP Service for email delivery ingredient and emailpassword + emailverification recipes.
-   [ ] …
> feat: Add SMTP Service for email delivery ingredient

- supertokens_python/supertokens.py
- supertokens_python/utils.py
- tests/emailpassword/test_signin.py
- tests/test_passwordless.py
- tests/test_utils.py
- tests/usermetadata/test_metadata.py
feat: Add test for shallow merge in usermetadata recipe
-   [ ] Had installed and ran the pre-commit …
> feat: Add test for shallow merge in usermetadata recipe

- CHANGELOG.md
- CONTRIBUTING.md
Updated Project Setup, Modifying Code and Testing sections in the CONTRIBUTING.md
None
None
None
-   If no …
> chore: updates CONTRIBUTING.md

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/thirdparty/api/implementation.py
- supertokens_python/recipe/thirdparty/provider.py
- supertokens_python/recipe/thirdparty/providers/apple.py
- supertokens_python/recipe/thirdparty/providers/discord.py
- supertokens_python/recipe/thirdparty/providers/facebook.py
- supertokens_python/recipe/thirdparty/providers/github.py
- supertokens_python/recipe/thirdparty/providers/google.py
- supertokens_python/recipe/thirdparty/providers/google_workspaces.py
- supertokens_python/recipe/thirdparty/providers/okta.py
- supertokens_python/recipe/thirdparty/utils.py
- tests/auth-react/django3x/mysite/settings.py
- tests/auth-react/django3x/polls/views.py
- tests/auth-react/fastapi-server/app.py
- tests/auth-react/flask-server/app.py
Changes `Provider` class to get the client using a function so that it can be changed via a user_context. 
Type changes in docs
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the …
> Third party provider change

- CHANGELOG.md
- supertokens_python/recipe/thirdparty/api/implementation.py
- supertokens_python/recipe/thirdparty/interfaces.py
- supertokens_python/recipe/thirdparty/recipe_implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/api/implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/api/thirdparty_api_implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/interfaces.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/third_party_recipe_implementation.py
- supertokens_python/recipe/thirdpartypasswordless/api/implementation.py
- supertokens_python/recipe/thirdpartypasswordless/api/thirdparty_api_implementation.py
- supertokens_python/recipe/thirdpartypasswordless/interfaces.py
- supertokens_python/recipe/thirdpartypasswordless/recipeimplementation/implementation.py
- supertokens_python/recipe/thirdpartypasswordless/recipeimplementation/third_party_recipe_implementation.py
Interface return types cleanup thirdparty …
> refactor: Interface return types cleanup thirdparty

- CHANGELOG.md
- supertokens_python/recipe/thirdpartyemailpassword/api/emailpassword_api_impementation.py
- supertokens_python/recipe/thirdpartyemailpassword/api/implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/api/thirdparty_api_implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/interfaces.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/email_password_recipe_implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/third_party_recipe_implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/syncio/__init__.py
Added Result/Response classes to use Recipe's User class
-   If no such branch exists, then create one from …
> refactor: Added Result/Response classes to use Recipe's User class

- CHANGELOG.md
- supertokens_python/recipe/jwt/api/implementation.py
- supertokens_python/recipe/jwt/asyncio/__init__.py
- supertokens_python/recipe/jwt/interfaces.py
- supertokens_python/recipe/jwt/recipe_implementation.py
- supertokens_python/recipe/jwt/syncio/__init__.py
- supertokens_python/recipe/openid/asyncio/__init__.py
- supertokens_python/recipe/openid/interfaces.py
- supertokens_python/recipe/openid/recipe_implementation.py
- supertokens_python/recipe/openid/syncio/__init__.py
- supertokens_python/recipe/session/asyncio/__init__.py
- supertokens_python/recipe/session/syncio/__init__.py
- supertokens_python/recipe/session/with_jwt/utills.py
- tests/jwt/test_create_jwt_feature.py
- tests/jwt/test_override.py
Interface return types cleanup jwt
-   If no such branch exists, then create one from the latest released …
> refactor: Interface return types cleanup jwt

- CHANGELOG.md
- supertokens_python/recipe/session/interfaces.py
- supertokens_python/recipe/session/recipe_implementation.py
- supertokens_python/recipe/session/session_functions.py
Interface return types cleanup session …
> refactor: Interface return types cleanup session

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/supertokens.py
bug fix telemetry API when calling the init function
> fix: telemetry API when calling the init function 

- tests/frontendIntegration/django3x/polls/urls.py
- tests/frontendIntegration/django3x/polls/views.py
- tests/frontendIntegration/fastapi-server/app.py
- tests/frontendIntegration/flask-server/app.py
> fix: added /update-jwt-with-handle endpoint in  test servers for integration tests

- CHANGELOG.md
- supertokens_python/recipe/emailpassword/syncio/__init__.py
- supertokens_python/recipe/emailverification/syncio/__init__.py
- supertokens_python/recipe/jwt/syncio/__init__.py
- supertokens_python/recipe/openid/syncio/__init__.py
- supertokens_python/recipe/thirdparty/syncio/__init__.py
Fix bugs in syncio functions across all the recipes …
> fix: Improve syncio functions across all the recipes

- supertokens_python/recipe/emailverification/api/implementation.py
- tests/emailpassword/test_emailverify.py
fix: Fix email verification link and update relevant tests
-   In …
> fix: Fix email verification link and update relevant tests

- supertokens_python/recipe/passwordless/emaildelivery/services/backward_compatibility/__init__.py
> fix: fixed data for passwordless login api

- tests/passwordless/test_emaildelivery.py
- tests/passwordless/test_smsdelivery.py
- tests/thirdpartypasswordless/test_emaildelivery.py
- tests/thirdpartypasswordless/test_smsdelivery.py
> fix: Unittest fix

- supertokens_python/recipe/session/api/implementation.py
- tests/auth-react/django3x/mysite/utils.py
- tests/auth-react/django3x/polls/views.py
- tests/auth-react/fastapi-server/app.py
- tests/auth-react/flask-server/app.py
- fixed SignOutOkayResponse bug
- updated auth react tests for frameworks
> refactor: updated auth react test code

- CHANGELOG.md
- CONTRIBUTING.md
Update `CONTRIBUTING.md` and mention in `CHANGELOG`
- …
> docs: Update CONTRIBUTING.md and mention in CHANGELOG

- CHANGELOG.md
- supertokens_python/recipe/emailpassword/api/email_exists.py
- supertokens_python/recipe/emailpassword/api/generate_password_reset_token.py
- supertokens_python/recipe/emailpassword/api/password_reset.py
- supertokens_python/recipe/emailpassword/api/signin.py
- supertokens_python/recipe/emailpassword/api/signup.py
- supertokens_python/recipe/emailverification/api/email_verify.py
- supertokens_python/recipe/emailverification/api/generate_email_verify_token.py
- supertokens_python/recipe/jwt/api/jwks_get.py
- supertokens_python/recipe/openid/api/open_id_discovery_configuration_get.py
- supertokens_python/recipe/passwordless/api/consume_code.py
- supertokens_python/recipe/passwordless/api/create_code.py
- supertokens_python/recipe/passwordless/api/email_exists.py
- supertokens_python/recipe/passwordless/api/phone_number_exists.py
- supertokens_python/recipe/passwordless/api/resend_code.py
- supertokens_python/recipe/session/api/refresh.py
- supertokens_python/recipe/session/api/signout.py
- supertokens_python/recipe/thirdparty/api/apple_redirect.py
- supertokens_python/recipe/thirdparty/api/authorisation_url.py
- supertokens_python/recipe/thirdparty/api/signinup.py
- supertokens_python/utils.py
- tests/__init__.py
- tests/test_user_context.py
feat: Add default user context
-   Equivalent node PR https://github.com/supertokens/supertokens-node/pull/338/files
-   In …
> feat: Add default user context

- CHANGELOG.md
- examples/with-django/with-thirdpartyemailpassword/project/settings.py
- examples/with-fastapi/with-thirdpartyemailpassword/main.py
- examples/with-flask/with-thirdpartyemailpassword/app.py
- frontendDriverInterfaceSupported.json
- tests/sessions/claims/test_assert_claims.py
- tests/sessions/claims/test_create_new_session.py
- tests/sessions/claims/test_get_claim_value.py
- tests/sessions/claims/test_primitive_array_claim.py
- tests/sessions/claims/test_primitive_claim.py
- tests/sessions/claims/test_validate_claims_for_session_handle.py
- tests/sessions/claims/test_verify_session.py
- tests/sessions/claims/test_with_jwt.py
- tests/sessions/claims/utils.py
- tests/userroles/test_claims.py
- tests/utils.py
Fixing and adding tests related to session claims. 
- …
> feat: Session claims (test+changelog+example)

- .circleci/config_continue.yml
- CHANGELOG.md
- frontendDriverInterfaceSupported.json
- supertokens_python/recipe/session/recipe.py
- tests/auth-react/fastapi-server/app.py
- tests/userroles/test_claims.py
Fix flaky test in session claims …
> fix: session claims

- supertokens_python/recipe/session/api/implementation.py
- supertokens_python/recipe/session/interfaces.py
- tests/auth-react/django3x/mysite/utils.py
- tests/auth-react/fastapi-server/app.py
- tests/auth-react/flask-server/app.py
- tests/sessions/claims/test_verify_session.py
Fix failing unit tests
-   [ ] Had installed and ran …
> test: Fix failing unit tests

- tests/auth-react/flask-server/app.py
fix: session claims auth-react tests for Flask
-   [ ] …
> fix: session claims auth-react tests for Flask

- CHANGELOG.md
- examples/with-fastapi/with-thirdpartyemailpassword/main.py
- supertokens_python/recipe/emailverification/recipe.py
- tests/emailpassword/test_emailverify.py
- Email verification endpoint now clears the session if called with a deleted/unknown user
- Sign out now always clears cookies - even if there is no valid session attached
-   https://github.com/supertokens/supertokens-auth-react/issues/580
Added tests …
> feat: Clear session for deleted users

- tests/auth-react/django3x/mysite/utils.py
- tests/auth-react/fastapi-server/app.py
- tests/auth-react/flask-server/app.py
- tests/utils.py
Reset dashboard after test (auth react + unit)
This should fix the failing tests …
> fix: Reset dashboard after test

- tests/Fastapi/test_fastapi.py
fix: FastAPI root path test failure
-   [ ] Issue …
> fix: FastAPI root path test failure

- supertokens_python/recipe/emailverification/recipe.py
Disallow None in ev claim default max age
-   [ ] Had …
> fix: Disallow None in ev claim default max age

- CHANGELOG.md
- supertokens_python/recipe/thirdparty/providers/google.py
- supertokens_python/recipe/thirdparty/providers/google_workspaces.py
Updated google token endpoint
-   [ ] ~~`coreDriverInterfaceSupported.json` file has been updated (if needed)~~
-   ~~Along with the associated array in `supertokens_python/constants.py`~~
-   [ ] ~~`frontendDriverInterfaceSupported.json` file has been updated (if needed)~~
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the …
> fix: updated google token endpoint

- tests/frontendIntegration/django2x/polls/urls.py
- tests/frontendIntegration/django2x/polls/views.py
- tests/frontendIntegration/django3x/polls/urls.py
- tests/frontendIntegration/django3x/polls/views.py
Fix Django frontend integration tests
-   [ ] Issue …
> test: Fix Django frontend integration tests

- CHANGELOG.md
Update CHANGELOG to mention jsonschema removal from requirements
-   https://github.com/supertokens/supertokens-python/pull/250
-   In …
> chore: Update CHANGELOG to mention jsonschema removal from requirements

- tests/sessions/claims/test_with_jwt.py
test: Check jwt payload after merging claim in access token payload
-   https://github.com/supertokens/supertokens-node/issues/423
-   In …
> test: Check jwt payload after merging claim in access token payload

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/emailverification/recipe.py
- tests/emailpassword/test_emailverify.py
Update session claim in email verification token generation API
-  https://github.com/supertokens/supertokens-node/issues/419
-   In …
> fix: Update session claim in email verification token generation API

- README.md
Add monthly download stats badge for supertokens-python lib
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, …
> feat: Add monthly download stats badge for supertokens-python

- supertokens_python/recipe/dashboard/api/userdetails/user_sessions_get.py
Remove unused import for linter to succeed
-   [ ] …
> refactor: Remove unused import

- Makefile
- dev-requirements.txt
Add pyest-rerunfailures to minimize impact of flasky tests
-   [x] Had installed and ran the …
> feat: Add pyest-rerunfailures to minimize impact of flasky tests

- tests/frontendIntegration/django2x/templates/index.html
- tests/frontendIntegration/django3x/templates/index.html
- tests/frontendIntegration/fastapi-server/templates/index.html
- tests/frontendIntegration/flask-server/templates/index.html
- tests/sessions/test_auth_mode.py
Fix frontend integration and unit test failures
- …
> fix: Fix frontend integration and unit test failures

- tests/Django/settings.py
- tests/Django/test_django.py
- tests/Flask/test_flask.py
- tests/thirdparty/test_thirdparty.py
Add tests for thirdparty parsing …
> test: Add tests for thirdparty

- CHANGELOG.md
- coreDriverInterfaceSupported.json
- setup.py
- supertokens_python/constants.py
Email password login for dashboard recipe
https://github.com/supertokens/dashboard/issues/55
All existing tests pass
None …
> feat: Email password login for dashboard

- CHANGELOG.md
- examples/with-django/with-thirdpartyemailpassword/sampleapp/views.py
- examples/with-fastapi/with-thirdpartyemailpassword/main.py
- examples/with-flask/with-thirdpartyemailpassword/app.py
- supertokens_python/recipe/dashboard/interfaces.py
- supertokens_python/recipe/session/asyncio/__init__.py
- supertokens_python/recipe/session/interfaces.py
- supertokens_python/recipe/session/recipe_implementation.py
- supertokens_python/recipe/session/session_class.py
- supertokens_python/recipe/session/session_functions.py
- supertokens_python/recipe/session/syncio/__init__.py
- supertokens_python/recipe/session/with_jwt/recipe_implementation.py
- tests/auth-react/django3x/polls/views.py
- tests/auth-react/fastapi-server/app.py
- tests/auth-react/flask-server/app.py
- tests/frontendIntegration/django2x/polls/views.py
- tests/frontendIntegration/django3x/polls/views.py
- tests/frontendIntegration/fastapi-server/app.py
- tests/frontendIntegration/flask-server/app.py
- tests/sessions/claims/utils.py
- tests/test_session.py
- tests/test_user_context.py
Rename sessionData related vars to clarity interaction with DB
-   https://github.com/supertokens/supertokens-node/pull/519
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the …
> refactor: Rename session_data related vars to clarify interaction with DB

- tests/Django/test_django.py
- tests/Fastapi/test_fastapi.py
- tests/Flask/test_flask.py
- tests/users.json
- tests/utils.py
Added tests for dashboard rercipe
**Tests added**
- tags
- email=t (users = 5)
- email=iresh (users = 0)
- email=john;iresh (users = 1)
- phone=+1
- phone=1(
- provider=google
- provider=google&phone=1
-   [ ] Had installed and …
> test: Dashboard search tests

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/emailverification/emaildelivery/services/smtp/email_verify_email.py
> fix: verify email updated

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/emailpassword/asyncio/__init__.py
- supertokens_python/recipe/emailpassword/interfaces.py
- supertokens_python/recipe/emailpassword/recipe.py
- supertokens_python/recipe/emailpassword/recipe_implementation.py
- supertokens_python/recipe/emailpassword/syncio/__init__.py
- supertokens_python/recipe/thirdpartyemailpassword/asyncio/__init__.py
- supertokens_python/recipe/thirdpartyemailpassword/interfaces.py
- supertokens_python/recipe/thirdpartyemailpassword/recipe.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/email_password_recipe_implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/syncio/__init__.py
- tests/emailpassword/test_updateemailorpassword.py
Added optional password validation in `update_email_or_password` function.
- https://github.com/supertokens/supertokens-node/issues/549 (same implemented in python)
-   [ ] Changes to the version if …
> feat: optional password validation in update_email_or_password

- supertokens_python/recipe/session/session_request_functions.py
Fix failing tests after merging https://github.com/supertokens/supertokens-python/pull/323/files
-   To know which one it is, run find the latest released tag …
> test: Fix failing tests

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/emailverification/recipe.py
- supertokens_python/recipe/session/access_token.py
- supertokens_python/recipe/session/recipe_implementation.py
- supertokens_python/recipe/session/session_class.py
- supertokens_python/recipe/session/session_request_functions.py
Add extra debug logs
-   If no such branch exists, then create one from the latest released branch.
-   [ ] …
> chores: Add extra debug logs

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/emailverification/emaildelivery/services/smtp/email_verify_email.py
- supertokens_python/recipe/passwordless/emaildelivery/services/smtp/pless_login_email.py
-   [xx] Changes to the version if needed …
> feat: email templates updated

- supertokens_python/recipe/emailverification/emaildelivery/services/smtp/email_verify_email.py
> fix: added missing id

- supertokens_python/recipe/emailpassword/emaildelivery/services/smtp/password_reset_email.py
> fix: Email templates superhuman

- supertokens_python/recipe/session/utils.py
> feat: anti_csrf default to VIA_CUSTOM_HEADER [APP_INFO #1]

- CHANGELOG.md
- supertokens_python/framework/django/django_middleware.py
- supertokens_python/framework/fastapi/fastapi_middleware.py
- supertokens_python/framework/flask/flask_middleware.py
- supertokens_python/recipe/session/cookie_and_header.py
- supertokens_python/recipe/session/interfaces.py
- supertokens_python/recipe/session/recipe.py
- supertokens_python/recipe/session/session_class.py
- supertokens_python/recipe/session/session_request_functions.py
- supertokens_python/recipe/session/utils.py
- supertokens_python/supertokens.py
> feat: Cookie same site should accept function, string, or None [APP_INFO #2]

- CHANGELOG.md
- supertokens_python/recipe/jwt/interfaces.py
- supertokens_python/recipe/jwt/recipe_implementation.py
- supertokens_python/recipe/openid/asyncio/__init__.py
- supertokens_python/recipe/openid/interfaces.py
- supertokens_python/recipe/openid/recipe_implementation.py
- supertokens_python/recipe/openid/syncio/__init__.py
- supertokens_python/recipe/openid/utils.py
- supertokens_python/recipe/session/asyncio/__init__.py
- supertokens_python/recipe/session/syncio/__init__.py
- tests/jwt/test_override.py
> feat: App info rafactor open id changes [APP_INFO #5]

- supertokens_python/recipe/session/utils.py
- supertokens_python/supertokens.py
> feat: Check if input function for origin/api_doamin/cookie_same_site is awaitable [APP_INFO #6]

- supertokens_python/recipe/jwt/utils.py
- supertokens_python/recipe/passwordless/recipe.py
- supertokens_python/supertokens.py
> feat: App info/origin type change [APP_INFO #7]

- supertokens_python/recipe/thirdpartyemailpassword/recipe.py
- supertokens_python/recipe/thirdpartypasswordless/recipe.py
- tests/thirdparty/test_authorisation_url_feature.py
- tests/thirdpartyemailpassword/test_authorisation_url_feature.py
- tests/thirdpartypasswordless/test_authorisation_url_feature.py
allows empty provider list
-   https://github.com/supertokens/supertokens-node/pull/652
-   If no such …
> allows empty provider list

- supertokens_python/recipe/thirdparty/providers/active_directory.py
- supertokens_python/recipe/thirdparty/providers/custom.py
- supertokens_python/recipe/thirdparty/providers/facebook.py
- supertokens_python/recipe/thirdparty/providers/google.py
- supertokens_python/recipe/thirdparty/providers/okta.py
- tests/thirdparty/test_multitenancy.py
user info map
-   https://github.com/supertokens/supertokens-node/pull/651
-   If no such branch exists, …
> fix: user info map

- supertokens_python/recipe/thirdparty/api/implementation.py
Fix apple redirect
-   https://github.com/supertokens/supertokens-golang/pull/335
-   If no such branch …
> fix: apple redirect

- CHANGELOG.md
- setup.py
Update CHANGELOG to mention multitenancy and thirdparty changes
Related to https://github.com/supertokens/supertokens-node/blob/master/CHANGELOG.md
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` …
> chores: Update CHANGELOG to mention multitenancy and thirdparty changes

- supertokens_python/recipe/multitenancy/syncio/__init__.py
Fix docs building
-   If no such branch exists, then create …
> fix: Docs building

- tests/test_session.py
Fix failing test for the 0.14 patch release …
> test: Fix failing test for the 0.14 patch release

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/dashboard/api/implementation.py
- tests/dashboard/test_dashboard.py
This PR replicates the changes done in the https://github.com/supertokens/supertokens-node/pull/795
- https://github.com/supertokens/supertokens-node/pull/795
- …
> fix: dashboard connection uri path

- tests/frontendIntegration/django2x/polls/urls.py
- tests/frontendIntegration/django2x/polls/views.py
- tests/frontendIntegration/django3x/polls/urls.py
- tests/frontendIntegration/django3x/polls/views.py
- tests/frontendIntegration/fastapi-server/app.py
- tests/frontendIntegration/flask-server/app.py
> fix: cicd test

- tests/frontendIntegration/django2x/polls/views.py
> fix: django2x

- .circleci/config_continue.yml
> fix: cicd fix

- .circleci/config_continue.yml
> fix: build fix for drf tests

- .circleci/setupAndTestWithFrontendWithDrfSync.sh
- setup.py
> fix: using gunicorn for drf sync

- tests/frontendIntegration/django2x/mysite/settings.py
- tests/frontendIntegration/django3x/mysite/settings.py
- tests/frontendIntegration/drf_async/mysite/settings.py
- tests/frontendIntegration/drf_sync/mysite/settings.py
> test: fix tests by adding localhost as an allowed host to test servers

- tests/emailpassword/test_emailverify.py
> fix: unit test

- .circleci/config.yml
> fix: cicd image

- CHANGELOG.md
- dev-requirements.txt
- setup.py
- supertokens_python/constants.py
> fix: requirement for docs

- tests/auth-react/fastapi-server/app.py
- tests/test_logger.py
- fix: updates line num for logger test
- fix: updates deprecated import from starlette
-   [ ] Had …
> fix: failing tests in CI

- .circleci/config.yml
- CHANGELOG.md
- Also upgrades `poetry` and it's dependency - `clikit`
- These seem to come from the `circleci:python` image
-   In …
> build: upgrade `setuptools`/`pip` in `publish` job

- .circleci/config_continue.yml
- tests/test-server/app.py
> fix: circleCI unittest script make usage

- .circleci/config.yml
> fix: makes `publish` package installs consistent

- .circleci/installJava.sh
- Upgrade to Java 21
-   [ ] Had installed and ran the …
> update: CircleCI java version

- supertokens_python/recipe/dashboard/api/analytics.py
> feat: adds Python version to telemetry

- .github/workflows/pipeline-release-tag.yml
- Fetches jobs from current run and skips them from checks
-   In …
> fix: release pipeline status checks

- .github/workflows/pipeline-release-tag.yml
> fix: `wheel` dependency, status check

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/dashboard/api/multitenancy/utils.py
- supertokens_python/recipe/dashboard/api/userdetails/user_put.py
- supertokens_python/recipe/dashboard/utils.py
- supertokens_python/recipe/multitenancy/api/implementation.py
- supertokens_python/recipe/multitenancy/interfaces.py
> feat: adds webauthn support to the dashboard recipe

- CHANGELOG.md
- supertokens_python/__init__.py
- supertokens_python/asyncio/__init__.py
- supertokens_python/recipe/multifactorauth/types.py
- supertokens_python/supertokens.py
- supertokens_python/syncio/__init__.py
- tests/test_mfa.py
- Moves is_recipe_initialized to supertokens.asyncio
- Cleans up supertokens __init__ file to reduce redundancy
- Adds test to ensure FactorIds class and method are in sync
ref: supertokens/supertokens-node#1021 …
> feat: adds util function to get available first factors

- .github/workflows/auth-react-test-1-django.yml
- .github/workflows/auth-react-test-1-fastapi.yml
- .github/workflows/auth-react-test-1-flask.yml
- .github/workflows/auth-react-test-3.yml
- .github/workflows/backend-sdk-testing.yml
- .github/workflows/unit-test.yml
- .github/workflows/website-test.yml
- CHANGELOG.md
- compose.yml
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/webauthn/recipe.py
- Fixes minor issues with email selection logic
- Updates post init callbacks to use webauthn factor id
- Updates `docker-compose` to use `supertokens-dev-postgresql` instead of `supertokens-core`
- Updates workflows to use new `get-versions` action …
> fix: webauthn mfa integration
