supertokens/supertokens-python

- .circleci/config.yml
- CHANGELOG.md
- Makefile
- setup.py
- supertokens_python/constants.py
- supertokens_python/framework/django/framework.py
- supertokens_python/framework/fastapi/fastapi_middleware.py
- supertokens_python/framework/fastapi/framework.py
- supertokens_python/framework/flask/flask_middleware.py
- supertokens_python/framework/flask/framework.py
- supertokens_python/recipe/thirdparty/providers/apple.py
FIxes a bug where all frameworks dependencies needed to be added by the user.
-   https://github.com/supertokens/supertokens-python/issues/82
Added separate installation steps for each framework which is run when running auth-react and website tests
None
-   To know which one it is, run find the latest …
> fix: separates out installation for tests and fixes dependencies on frameworks

- CHANGELOG.md
- supertokens_python/framework/django/django_request.py
- supertokens_python/framework/fastapi/fastapi_request.py
- supertokens_python/framework/flask/flask_middleware.py
- supertokens_python/framework/flask/flask_request.py
- supertokens_python/framework/request.py
- supertokens_python/recipe/session/framework/django/asyncio/__init__.py
- supertokens_python/recipe/session/framework/django/syncio/__init__.py
- supertokens_python/recipe/session/framework/fastapi/__init__.py
- supertokens_python/recipe/session/framework/flask/__init__.py
- tests/Django/test_django.py
- tests/Fastapi/test_fastapi.py
- tests/Flask/test_flask.py
Fixes issue where we were not setting the supertokens object to `None` in case of optional session verification
-   https://github.com/supertokens/supertokens-python/issues/90
Added new tests for all supported frameworks with optional session verification API
None
-   To know which one it is, run find the …
> fix: https://github.com/supertokens/supertokens-python/issues/90

- CHANGELOG.md
- examples/with-fastapi/with-thirdpartyemailpassword/main.py
- setup.py
- supertokens_python/constants.py
- supertokens_python/framework/fastapi/__init__.py
- supertokens_python/framework/fastapi/fastapi_middleware.py
- supertokens_python/framework/flask/flask_response.py
- tests/Fastapi/test_fastapi.py
- tests/auth-react/fastapi-server/app.py
- tests/emailpassword/test_emailexists.py
- tests/emailpassword/test_emailverify.py
- tests/emailpassword/test_passwordreset.py
- tests/emailpassword/test_signin.py
- tests/frontendIntegration/fastapi-server/app.py
- tests/jwt/test_get_JWKS.py
- tests/jwt/test_override.py
- tests/test_middleware.py
- tests/test_user_context.py
Removes dependency from framework being used. This is a breaking change cause the way fastapi middleware was being exposed needed to be changed cause we couldn't import `starlette` on the top level.
> fix!: removes unnecessary dependencies + changes fastapi middleware import

- .circleci/config.yml
- CHANGELOG.md
- Makefile
- setup.py
- supertokens_python/constants.py
Expand the allowed versions for the dependency `httpx`. We are importing exactly 4 classes: `AsyncClient, ConnectTimeout, NetworkError, and Response`
I've tried my best to verify the code from https://github.com/encode/httpx and read the chagelogs for any breaking change in the above mentioned classes. 
After this relaxation of the version, the https://github.com/supertokens/supertokens-python/issues/98 is gone.
`supertokens-python` and `fastapi-mail` can now co-exist :)
- https://github.com/supertokens/supertokens-python/issues/98
Screenshot provided above.
-   [ ] `frontendDriverInterfaceSupported.json` …
> fix: Expands allowed version range for dependency httpx

- setup.py
setup.py: Adding missing dotenv in framework specific dependencies
-   To know which one it is, run find the latest released tag (`git tag`) in the format …
> fix: Add missing dotenv from framework specific dependencies

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/passwordless/interfaces.py
- supertokens_python/recipe/passwordless/recipe_implementation.py
- tests/test_passwordless.py
The phone number in the passwordless OTP recipe was getting stored in the email field. This PR fixes that bug. 
-   Fixes https://github.com/supertokens/supertokens-core/issues/416
- Added `test_passwordless.py` file
-   [ ] …
> fix: Use Passwordless OTP recipe phone number field and add test

- tests/test_passwordless.py
Fix failure of test_passwordless_otp if core version is < 2.11.0 (Passwordless recipe didn't exist before 2.11.0)
-   In …
> fix: Skip test_passwordless_otp test if core version < 2.11.0

- CHANGELOG.md
- supertokens_python/supertokens.py
- supertokens_python/utils.py
- tests/emailpassword/test_signin.py
- tests/test_passwordless.py
Rename compare_version to get_max_version for readability
-   [ ] Had installed and ran the pre-commit …
> feat: Rename compare_version to get_max_version for readability

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/usermetadata/syncio/__init__.py
The usermetadata functions in the `syncio` file where exported as `async` functions. Changed them to be exported as `sync` functions - as they should have been.
We should write a github PR check to make sure that the keyword "async def" doesn't appear in the `syncio.py` files
-   To know which one it is, run …
> fix: makes all functions in syncio usermetadata into sync

- CHANGELOG.md
- supertokens_python/framework/fastapi/fastapi_response.py
New version of FastAPI was assuming the content-length to be zero and failing to respond. Explicitly added content-length header in our FastAPI response wrapper.
Have tested agains latest and old version. This header was not required with the old version of FastAPI, but this change safely works with old version of it as well.
-   [ ] Issue this PR against the latest non released …
> fix: Fixed content length for FastAPI Response Wrapper

- CHANGELOG.md
- supertokens_python/recipe/emailpassword/types.py
Emailpassword types has a `User` class has `third_party_info` always set to `None` which is not required. Removed it …
> refactor: removed thirdparty_info from emailpassword `User`

- CHANGELOG.md
- supertokens_python/recipe/usermetadata/interfaces.py
- supertokens_python/recipe/usermetadata/recipe_implementation.py
- tests/usermetadata/test_metadata.py
Normalised return types for usermetadata, to return exact types instead of Abstract types.
-   If no such …
> refactor: normalised return types for usermetadata

- CHANGELOG.md
- supertokens_python/recipe/emailpassword/utils.py
- tests/input_validation/test_input_validation.py
User might not have enabled linting with their IDE, might end up passing wrong types which is not caught early within the SDK. Added type checks for the emailpassword recipe.
-   https://github.com/supertokens/supertokens-python/issues/128
Added unit tests.
-   [ ] Had …
> refactor: added type checks for init params for emailpassword

- CHANGELOG.md
- supertokens_python/recipe/thirdpartyemailpassword/interfaces.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/syncio/__init__.py
- supertokens_python/recipe/thirdpartypasswordless/api/implementation.py
- supertokens_python/recipe/thirdpartypasswordless/api/thirdparty_api_implementation.py
- supertokens_python/recipe/thirdpartypasswordless/asyncio/__init__.py
- supertokens_python/recipe/thirdpartypasswordless/interfaces.py
- supertokens_python/recipe/thirdpartypasswordless/syncio/__init__.py
Exporting re-used classes from `passwordless` interface and `thirdparty` interface in the `thirdpartypasswordless` interface. Also, cleaned up imports for code clarity. …
> refactor: exported re-used classes and cleaning up imports for clarity (thirdpartypasswordless)

- CHANGELOG.md
- supertokens_python/recipe/thirdpartyemailpassword/interfaces.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/syncio/__init__.py
Exporting re-used classes from `emailpassword` interface and `thirdparty` interface in the `thirdpartyemailpassword` interface. Also, cleaned up imports for code clarity. …
> refactor: exported re-used classes and cleaning up imports for clarity (thirdpartyemailpassword)

- CHANGELOG.md
- supertokens_python/recipe/emailverification/utils.py
- tests/input_validation/test_input_validation.py
User might not have enabled linting with their IDE, might end up passing wrong types which is not caught early within the SDK. Added type checks for the emailverification recipe.
-   https://github.com/supertokens/supertokens-python/issues/128
Added unit tests.
-   [ ] Had …
> refactor: added type checks for init params for emailverification

- CHANGELOG.md
- supertokens_python/recipe/openid/utils.py
- tests/input_validation/test_input_validation.py
User might not have enabled linting with their IDE, might end up passing wrong types which is not caught early within the SDK. Added type checks for the openid recipe.
-   https://github.com/supertokens/supertokens-python/issues/128
Added unit tests.
-   [ ] Had installed and …
> refactor: added type checks for init params for openid

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/logger.py
- supertokens_python/supertokens.py
- supertokens_python/utils.py
- tests/telemetry/test_telemetry.py
fix as follows:
- wrapped send_telemetry around try-except so that it won’t stop the app startup
- inside execute_async, determine running loop and execute based on the running mode
- also in execute_async throw out a warning if mode inconsistency is seen
Tested wrong and right modes with FastAPI, Flask and Django with both gunicorn (wsgi) and uvicorn (asgi). Ensured right warning is shown and app starts up correctly.
-   [ ] ~~`coreDriverInterfaceSupported.json` file has been updated (if needed)~~
-   ~~Along with the associated array in `supertokens_python/constants.py`~~
-   [ ] …
> fix: fixed execute_async to use real asyncio mode, handle send_telemetry exception silently

- CHANGELOG.md
- supertokens_python/recipe/session/utils.py
- tests/input_validation/test_input_validation.py
User might not have enabled linting with their IDE, might end up passing wrong types which is not caught early within the SDK. Added type checks for the session recipe. …
> refactor: added type checks for init params for session

- CHANGELOG.md
- supertokens_python/recipe/thirdparty/utils.py
- tests/input_validation/test_input_validation.py
User might not have enabled linting with their IDE, might end up passing wrong types which is not caught early within the SDK. Added type checks for the thirdparty recipe. …
> refactor: added type checks for init params for thirdparty

- CHANGELOG.md
- supertokens_python/recipe/thirdpartyemailpassword/utils.py
- tests/input_validation/test_input_validation.py
User might not have enabled linting with their IDE, might end up passing wrong types which is not caught early within the SDK. Added type checks for the thirdpartyemailpassword recipe.
-   [ ] `frontendDriverInterfaceSupported.json` …
> refactor: added type checks for init params for thirdpartyemailpassword

- CHANGELOG.md
- supertokens_python/recipe/thirdpartypasswordless/utils.py
- tests/input_validation/test_input_validation.py
User might not have enabled linting with their IDE, might end up passing wrong types which is not caught early within the SDK. Added type checks for the thirdpartypasswordless recipe.
-   [ ] `frontendDriverInterfaceSupported.json` file …
> refactor: added type checks for init params for thirdpartypasswordless

- CHANGELOG.md
- supertokens_python/recipe/usermetadata/utils.py
- tests/input_validation/test_input_validation.py
User might not have enabled linting with their IDE, might end up passing wrong types which is not caught early within the SDK. Added type checks for the usermetadata recipe. …
> refactor: added type checks for init params for usermetadata

- tests/telemetry/test_telemetry.py
Updated the telemetry tests to check for specific warning message. We should not be comparing all warning messages to the one we are looking for.
- Ran telemetry tests about a 100 times and ensured it never failed
- Ran telemetry tests upon reverting my original fix and ensured the test failed
-   [ ] ~~Changelog has been updated~~
-   [ ] ~~`coreDriverInterfaceSupported.json` file has been updated (if needed)~~
-   ~~Along with the associated array in `supertokens_python/constants.py`~~
-   [ ] ~~`frontendDriverInterfaceSupported.json` file has been updated (if needed)~~
-   [ ] ~~Changes …
> fix: Telemetry test async issue

- tests/utils.py
Similar to golang:
```
command := fmt.Sprintf(`java -Djava.security.egd=file:/dev/urandom -classpath "./core/*:./plugin-interface/*" io.supertokens.Main ./ DEV host=%s port=%s test_mode`, host, port)
```
-   [ ] ~~Changelog has been updated~~
-   [ ] ~~`coreDriverInterfaceSupported.json` file has been updated (if needed)~~
-   ~~Along with the associated array in `supertokens_python/constants.py`~~
-   [ ] ~~`frontendDriverInterfaceSupported.json` file has been updated (if needed)~~
-   [ ] ~~Changes to the version if needed~~
-   ~~In `setup.py`~~
-   ~~In `supertokens_python/constants.py`~~
-   To know which one it is, run find the latest released tag (`git tag`) in …
> fix: startup supertokens process in test_mode

- CHANGELOG.md
- supertokens_python/recipe/thirdpartypasswordless/recipe.py
Changes `get_email_for_user_id ` in thirdpartypasswordless to take into account passwordless user email as well in case the dev wants to customise the thirdpartypasswordless recipe's email verification functions to take into account passwordless users as well.
-   https://discord.com/channels/603466164219281420/987701400433725440/988016274443489300
> fix: thirdpartypasswordless email verification fix

- CHANGELOG.md
- tests/usermetadata/test_metadata.py
Update usermetadata tests to ensure that utf8 chars are supported
Unlike the node PR, the code in `querier.py` was already correct and didn't need to be touched. So I just added the tests to ensure that it works. 
-   Equivalent of https://github.com/supertokens/supertokens-node/pull/339/files …
> test: Update usermetadata tests to ensure that utf8 chars are supported

- CHANGELOG.md
- tests/emailpassword/test_emailverify.py
- tests/test_passwordless.py
- tests/test_thirdpartypasswordless_delete_user.py
- tests/usermetadata/test_metadata.py
- tests/userroles/test_add_role_to_user.py
- tests/userroles/test_config.py
- tests/userroles/test_create_new_role_or_add_permissions.py
- tests/userroles/test_delete_role.py
- tests/userroles/test_get_permissions_for_role.py
- tests/userroles/test_get_roles_for_user.py
- tests/userroles/test_get_roles_that_have_permissions.py
- tests/userroles/test_get_users_that_have_role.py
- tests/userroles/test_remove_permissions_from_role.py
- tests/userroles/test_remove_user_role.py
test: Mark test as skipped if core version requirements are not met. 
Previously we just did a `return` and it was not possible to differentiate whether a test passed successfully or got skipped.
-   [ ] …
> test: Mark test as skipped if core version requirements are not met

- .circleci/config_continue.yml
- .circleci/setupAndTestWithFrontendWithDjango.sh
- Makefile
- setup.py
- tests/supertokens_python/test_supertokens_functions.py
Fix failing unit and django2x frontend integration tests
-   In …
> ci: Fix failing unit and django2x frontend integration tests

- CHANGELOG.md
- supertokens_python/recipe/session/session_class.py
- tests/test_session.py
Clear cookies when `revoke_session` is called
-   https://github.com/supertokens/supertokens-node/issues/343
-   In …
> fix: Clear cookies when revoke_session is called

- .circleci/setupAndTestWithFrontendWithDjango2x.sh
- setup.py
Fix integration test failure: 
- use `python3` instead of `python` (refers to 2.7 in the CI and this caused the failures)
- Fix python versions in setup.py
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if …
> ci: Fix integration test failure

- .circleci/setupAndTestWithFrontendWithDjango2x.sh
- setup.py
- tests/frontendIntegration/django2x/mysite/settings.py
- tests/frontendIntegration/django2x/requirements.txt
- tests/frontendIntegration/django3x/requirements.txt
Fix Django2x frontend integration tests
-   [ ] Had …
> ci: Fix Django2x frontend integration tests

- CHANGELOG.md
- Makefile
- dev-requirements.txt
- setup.py
- supertokens_python/querier.py
- supertokens_python/recipe/thirdparty/providers/apple.py
- supertokens_python/recipe/thirdparty/providers/discord.py
- supertokens_python/recipe/thirdparty/providers/facebook.py
- supertokens_python/recipe/thirdparty/providers/github.py
- supertokens_python/recipe/thirdparty/providers/google.py
Relax httpx, asgiref, and cryptography versions
-   https://github.com/supertokens/supertokens-python/issues/207
-   In …
> fix: Relax dependency versions in setup.py

- supertokens_python/recipe/session/api/implementation.py
- supertokens_python/recipe/session/asyncio/__init__.py
- supertokens_python/recipe/session/claim_base_classes/primitive_claim.py
- supertokens_python/recipe/session/framework/django/asyncio/__init__.py
- supertokens_python/recipe/session/framework/django/syncio/__init__.py
- supertokens_python/recipe/session/framework/fastapi/__init__.py
- supertokens_python/recipe/session/framework/flask/__init__.py
- supertokens_python/recipe/session/interfaces.py
- supertokens_python/recipe/session/recipe.py
- supertokens_python/recipe/session/recipe_implementation.py
- supertokens_python/recipe/session/session_class.py
- supertokens_python/recipe/session/syncio/__init__.py
- supertokens_python/recipe/session/utils.py
- supertokens_python/recipe/session/with_jwt/recipe_implementation.py
- tests/sessions/claims/test_assert_claims.py
- tests/sessions/claims/test_create_new_session.py
- tests/sessions/claims/test_get_claim_value.py
- tests/sessions/claims/test_primitive_claim.py
- tests/sessions/claims/test_remove_claim.py
- tests/sessions/claims/test_set_claim_value.py
- tests/sessions/claims/test_validate_claims_for_session_handle.py
- tests/sessions/claims/test_verify_session.py
- tests/sessions/claims/test_with_jwt.py
- tests/sessions/claims/utils.py
Refactor session claims and tests
-   [ ] Had …
> feat: Refactor session claims and tests

- CHANGELOG.md
- tests/test_session.py
test: Ensure that override work as expected for Session Container methods
-   In …
> test: Ensure that override work as expected for Session Container methods

- CHANGELOG.md
- supertokens_python/recipe/emailpassword/api/utils.py
- supertokens_python/recipe/emailpassword/utils.py
- tests/emailpassword/test_passwordreset.py
Send 400 instead of 500 on invalid request body
-   [ …
> fix(emailpassword): Send 400 on passing non-string email in request body

- tests/auth-react/django3x/mysite/utils.py
- tests/auth-react/django3x/polls/urls.py
- tests/auth-react/django3x/polls/views.py
- tests/auth-react/flask-server/app.py
fix session claims (django+flask auth-react tests)
- …
> test: Fix failing tests for django and flask

- CHANGELOG.md
- supertokens_python/ingredients/emaildelivery/services/smtp.py
- supertokens_python/ingredients/emaildelivery/types.py
Add smtp server login credentials in SMTPSettings
-   https://github.com/supertokens/supertokens-python/issues/217
-   In …
> feat: Add field for smtp server username in SMTPSettings

- CHANGELOG.md
- supertokens_python/recipe/emailverification/recipe.py
- supertokens_python/recipe/session/claim_base_classes/boolean_claim.py
- supertokens_python/recipe/session/claim_base_classes/primitive_array_claim.py
- supertokens_python/recipe/session/claim_base_classes/primitive_claim.py
- supertokens_python/recipe/userroles/recipe.py
- tests/sessions/claims/test_primitive_array_claim.py
- tests/sessions/claims/test_primitive_claim.py
refactor: Remove default max age from claim base classes and pass it from claims
-   https://github.com/supertokens/supertokens-node/pull/402
- …
> refactor: Remove default max age from claim base classes and pass it from claims

- CHANGELOG.md
- supertokens_python/framework/fastapi/fastapi_request.py
- supertokens_python/supertokens.py
- tests/Fastapi/test_fastapi.py
Fix repetition of root_path in supertokens mididdlware for fastapi
-   https://github.com/supertokens/supertokens-python/issues/230
-   In …
> fix: Repetition of root_path in supertokens mididdlware for fastapi

- setup.py
Relax the `typing_extensions` versions to be more compatible with other package requirements.
As per [our discord conversation](https://discord.com/channels/603466164219281420/1032111556915380305/1032160595694342186), this small change shouldn't cause any problems.
> fix: Relax typing_extensions version requirements

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/session/exceptions.py
- supertokens_python/recipe/session/utils.py
Add `to_json` method in ClaimValidationError class
This function will be used [lambda authorization](https://supertokens.com/docs/emailpassword/serverless/with-aws-lambda/authorizer) for python
-   [ ] …
> refactor: Add to_json method in ClaimValidationError

- CHANGELOG.md
- supertokens_python/recipe/session/utils.py
- tests/test_config_without_core.py
Same Site cookie between subdomains
-   https://github.com/supertokens/supertokens-python/issues/239
- …
> fix: Same Site cookie between subdomains

- dev-requirements.txt
- setup.py
After installing of supertokens-python I found that 2 packages were downgraded. I have researched that setuptools (65.5.0 -> 65.3.0) is downgraded due to jsonschema (4.16.0 -> 3.2.0).
I then looked at the use of `jsonschema` in the code and found that after the commit 4b725c7cb2de46f46c593d07bfb73b2ae4c62a5a, which was merged in v0.5.0, it's no longer used.
-   [x] Issue this PR …
> fix: Remove unused jsonschema package dependency

- CHANGELOG.md
- tests/test_session.py
Check behaviours of different variations for session revoke during session refresh
-   https://github.com/supertokens/supertokens-node/issues/418
-   In …
> test: Check behaviours of different variations for session revoke during session refresh

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/emailpassword/emaildelivery/services/backward_compatibility/__init__.py
- tests/emailpassword/test_emaildelivery.py
If the user is overriding the send_email function in emailpassword recipe to change the input email, their change will not get reflected since our implementation calls the get_user_by_id function which will reset their changed email.
So we reassign the input email to the result of calling getUserById …
> fix: send_email override issue

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/emailpassword/api/signup.py
- supertokens_python/recipe/emailpassword/exceptions.py
- tests/emailpassword/test_signup.py
Respond with field error on existing email id in signup api
-  https://github.com/supertokens/supertokens-python/issues/264
-   In …
> fix: Respond with field error on existing email id in signup api

- CHANGELOG.md
- supertokens_python/recipe/emailpassword/api/signup.py
Import SignUpPostOkResult instead of SignUpOkResult
- https://github.com/supertokens/supertokens-python/issues/264
- https://github.com/supertokens/supertokens-python/pull/265
-   [x] Changes to the …
> fix: Import SignUpPostOkResult instead of SignUpOkResult

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/dashboard/api/userdetails/user_get.py
- supertokens_python/recipe/dashboard/interfaces.py
- supertokens_python/recipe/dashboard/utils.py
- Updates dashboard version to 0.3
- Updates user GET API in dashboard recipe to handle if the recipe for the user being fetched was not initialised
-   
None
-   [x] Issue this PR against the latest non …
> fix: Update dashboard recipe user Get API

- CHANGELOG.md
- supertokens_python/framework/django/django_response.py
- tests/Django/test_django.py
Django cookie expiry time format is incorrect and inconsistent compared to other frameworks. Thankfully, @aprilis spotted and reported this issue. 
-   https://github.com/supertokens/supertokens-python/issues/267
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated …
> fix: Django cookie expiry time format

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
Relax pyjwt version constraints
-   https://github.com/supertokens/supertokens-python/issues/272
- …
> fix: Relax pyjwt version constraints

- CHANGELOG.md
- frontendDriverInterfaceSupported.json
- setup.py
- supertokens_python/constants.py
- supertokens_python/framework/django/django_response.py
- supertokens_python/framework/fastapi/fastapi_response.py
- supertokens_python/framework/flask/flask_response.py
- supertokens_python/framework/response.py
- supertokens_python/recipe/session/cookie_and_header.py
- supertokens_python/recipe/session/interfaces.py
- supertokens_python/recipe/session/utils.py
- tests/Django/test_django.py
- tests/Fastapi/test_fastapi.py
- tests/Flask/test_flask.py
- tests/test_session.py
- tests/utils.py
Clear session changes and CHANGELOG
-   [x] Had …
> fix: Clear session changes for header based auth

- tests/utils.py
Fix MagicMock import issue for python >=3.8. 
-   [ …
> fix: MagicMock import issue for python >=3.8

- CHANGELOG.md
- setup.py
Relax werkzeug version constraints
-   [ ] Issue …
> fix: Relax werkzeug version constraints

- supertokens_python/recipe/session/with_jwt/recipe_implementation.py
- supertokens_python/recipe/session/with_jwt/session_class.py
- tests/frontendIntegration/django2x/mysite/settings.py
- tests/frontendIntegration/django2x/polls/views.py
- tests/frontendIntegration/django3x/mysite/settings.py
- tests/frontendIntegration/django3x/polls/views.py
Fix failing supertokens-website frontendIntegration tests for Django
-   [x] Had installed and ran the …
> fix: Failing supertokens-website frontendIntegration tests

- .circleci/setupAndTestWithAuthReact.sh
- .circleci/setupAndTestWithAuthReactWithDjango.sh
- .circleci/setupAndTestWithAuthReactWithFlask.sh
- .circleci/setupAndTestWithFrontend.sh
- .circleci/setupAndTestWithFrontendWithDjango.sh
- .circleci/setupAndTestWithFrontendWithDjango2x.sh
- .circleci/setupAndTestWithFrontendWithFlask.sh
Run npm i after installing supertokens node to fix tests
-   In …
> fix: Run npm i after installing supertokens node to fix tests

- examples/with-django/with-thirdpartyemailpassword/project/settings.py
- examples/with-fastapi/with-thirdpartyemailpassword/main.py
- examples/with-flask/with-thirdpartyemailpassword/app.py
Use header based auth in examples. Previously, it was forcing to use `cookies`. Now using the default (i.e. headers)
-   [] Changelog has been updated => Not required since not changing the lib
- …
> chores: Use header based auth in examples

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/framework/fastapi/fastapi_request.py
- supertokens_python/framework/fastapi/fastapi_response.py
- supertokens_python/recipe/session/recipe_implementation.py
- supertokens_python/recipe/session/session_class.py
- supertokens_python/recipe/session/utils.py
- tests/test_session.py
Update access token cookie expiry logic and add comments.
Previously it was using seconds instead of ms. So instead of 100 years, it was being set to something like 47 years. …
> fix: Update access token cookie expiry logic and add comments

- supertokens_python/recipe/dashboard/__init__.py
Fixes the failing tests in PR #291 
None
ran tests
None
-   If no such branch exists, then create one from …
> fix: broken tests for dashboard email password PR

- CHANGELOG.md
- examples/with-django/with-thirdpartyemailpassword/project/settings.py
- examples/with-fastapi/with-thirdpartyemailpassword/main.py
- examples/with-flask/with-thirdpartyemailpassword/app.py
- Update example apps to also initialise the dashboard recipe
- 
NA
NA
-   If no such branch exists, then …
> chore: Add dashboard init to all example apps

- supertokens_python/recipe/dashboard/api/implementation.py
> feat: Cdi check

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/dashboard/api/userdetails/user_password_put.py
https://github.com/supertokens/supertokens-python/issues/312
- Tried changing password for multiple users to invoke the API
- Passed all existing tests
-   [x] Issue this PR against the latest non …
> fix: fixes user_password_put

- CHANGELOG.md
- setup.py
- supertokens_python/asyncio/__init__.py
- supertokens_python/constants.py
- supertokens_python/syncio/__init__.py
- tests/supertokens_python/test_supertokens_functions.py
Added missing arguments from get_users_newest_first and get_users_oldest_first …
> feat: added query support to get_users_newest_first and get_users_oldest_first

- Makefile
- supertokens_python/framework/django/django_request.py
- supertokens_python/framework/fastapi/fastapi_request.py
- supertokens_python/framework/flask/flask_request.py
- supertokens_python/recipe/session/asyncio/__init__.py
- supertokens_python/recipe/session/exceptions.py
- supertokens_python/recipe/session/jwks.py
- supertokens_python/recipe/session/recipe.py
- supertokens_python/recipe/session/session_class.py
- supertokens_python/recipe/session/session_functions.py
- supertokens_python/recipe/session/session_request_functions.py
- supertokens_python/utils.py
- tests/Fastapi/test_fastapi.py
- tests/frontendIntegration/django2x/polls/urls.py
- tests/frontendIntegration/django2x/polls/views.py
- tests/frontendIntegration/django3x/polls/urls.py
- tests/frontendIntegration/django3x/polls/views.py
- tests/frontendIntegration/fastapi-server/app.py
- tests/frontendIntegration/flask-server/app.py
- tests/sessions/claims/test_create_new_session.py
- tests/sessions/claims/test_remove_claim.py
- tests/sessions/claims/test_set_claim_value.py
- tests/sessions/test_access_token_v3.py
- tests/sessions/test_auth_mode.py
- tests/test_session.py
- tests/test_utils.py
Fix failing unit tests
-   If no such branch exists, then create one from the latest released branch.
-   [ …
> test: Fix failing unit tests for access token v3

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/session/interfaces.py
- supertokens_python/recipe/session/recipe_implementation.py
- supertokens_python/recipe/session/session_request_functions.py
Make loading access token from the request overrideable
-   If no such branch exists, then create one from …
> feat: Make loading access token from the request overrideable

- CHANGELOG.md
- setup.py
- supertokens_python/__init__.py
- supertokens_python/asyncio/__init__.py
- supertokens_python/constants.py
- supertokens_python/supertokens.py
- supertokens_python/syncio/__init__.py
- tests/test_user_context.py
- Added a helper function exported by the SuperTokens class that makes it easier to get the original request from the user context
- This reduces the boilerplate of always having to use usercontext._default.request and also allows the request to be strongly typed
- 
Added a test to make sure the new function works correctly
WIP
-   [x] Issue this PR against the latest non …
> feat: Add a helper function to read the original request from the user context inside overrides

- CHANGELOG.md
- supertokens_python/recipe/session/api/implementation.py
- supertokens_python/recipe/session/framework/flask/__init__.py
- tests/Flask/test_flask.py
Handle edge cases for `verify_session` decorator
-   https://github.com/supertokens/supertokens-python/issues/346 …
> fix: Handle edge cases for verify_session decorator

- tests/utils.py
Pass None to teardown function for min_version test wrapper
This will fix the failing tests.
-   If no such …
> fix: Pass None to teardown function for min_version test wrapper

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/thirdparty/providers/apple.py
- tests/thirdparty/test_thirdparty.py
Remove constraints on cryptography lib dependency. It's already a [dependency](https://github.com/jpadilla/pyjwt/blob/master/setup.cfg#L50) of `pyjwt` library. 
We were previously using it directly but looks like now it's just importing `RSAPublicKey` and even that is used just for  typing. So it should be safe to remove dependency constraints from our side.  
Added new test for Apple provider.
-   https://github.com/supertokens/supertokens-python/issues/351
-   In …
> fix: Remove constraints on cryptography lib dependency

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
Relax version constraints on httpx dependency
-   https://github.com/supertokens/supertokens-python/issues/358
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released …
> fix: Relax version constraints on httpx dependency

- CHANGELOG.md
update/fix migration guide in changelog
- https://github.com/supertokens/supertokens-node/pull/603
- https://github.com/supertokens/supertokens-node/pull/601
N/A Docs only change
N/A Docs only change
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find …
> docs: fix migration guide in changelog to be consistent with node

- supertokens_python/recipe/thirdparty/__init__.py
- supertokens_python/recipe/thirdparty/providers/apple.py
- supertokens_python/recipe/thirdpartyemailpassword/__init__.py
- supertokens_python/recipe/thirdpartyemailpassword/recipe.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/implementation.py
- supertokens_python/recipe/thirdpartypasswordless/__init__.py
- tests/thirdpartyemailpassword/test_email_delivery.py
- tests/thirdpartypasswordless/test_emaildelivery.py
Merge conflicts in thirdparty rework
-   If no such branch …
> fix: Merge conflicts in thirdparty rework

- CHANGELOG.md
- supertokens_python/recipe/session/session_request_functions.py
- tests/test_session.py
Anti csrf should happen only when access token is passed while session is optional
-   https://github.com/supertokens/supertokens-node/pull/610
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is …
> fix: Anti csrf should happen only when access token is passed while session is optional

- supertokens_python/recipe/session/framework/fastapi/__init__.py
- supertokens_python/recipe/session/framework/flask/__init__.py
- tests/Django/test_django.py
- tests/Flask/test_flask.py
- tests/sessions/claims/test_verify_session.py
Verify session should return 401 if not access token is sent and middelware isn't added. This PR adds a test for that. 
Updated FastAPI and Flask. Django was already handling this. 
-   To know which one it is, run find the latest released tag (`git tag`) in the …
> test: Verify session should return 401 if access token isn't sent and middleware isn't added

- tests/frontendIntegration/django2x/polls/urls.py
- tests/frontendIntegration/django2x/polls/views.py
- tests/frontendIntegration/django3x/polls/urls.py
- tests/frontendIntegration/django3x/polls/views.py
- tests/frontendIntegration/fastapi-server/app.py
- tests/frontendIntegration/flask-server/app.py
Fix frontend integration tests failure …
> test: Fix frontend integration tests failure

- tests/sessions/test_jwks.py
- tests/test_session.py
- tests/utils.py
- Test that `use_dynamic_access_token_signing_key` works as expected
- Test that `expose_access_token_to_frontend_in_cookie_based_auth` works as expected
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose …
> test: use_dynamic_access_token_signing_key should work as expected

- coreDriverInterfaceSupported.json
- supertokens_python/constants.py
- supertokens_python/normalised_url_path.py
- supertokens_python/recipe/multitenancy/api/implementation.py
- supertokens_python/recipe/multitenancy/asyncio/__init__.py
- supertokens_python/recipe/multitenancy/interfaces.py
- supertokens_python/recipe/multitenancy/recipe.py
- supertokens_python/recipe/multitenancy/recipe_implementation.py
- supertokens_python/recipe/multitenancy/syncio/__init__.py
- supertokens_python/recipe/session/constants.py
- supertokens_python/recipe/thirdparty/api/__init__.py
- supertokens_python/recipe/thirdparty/provider.py
- supertokens_python/recipe/thirdparty/providers/config_utils.py
- supertokens_python/recipe/thirdparty/providers/custom.py
- supertokens_python/recipe/thirdparty/recipe_implementation.py
- tests/multitenancy/test_tenants_crud.py
- tests/utils.py
Update multitenancy recipe
-   https://github.com/supertokens/supertokens-node/pull/594
-   If no such …
> fix: Update multitenancy recipe

- supertokens_python/recipe/multitenancy/interfaces.py
Make tenant id compulsory in TypeGetAllowedDomainsForTenantId
-   https://github.com/supertokens/supertokens-node/pull/597
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the …
> fix: Make tenant id compulsory in TypeGetAllowedDomainsForTenantId

- supertokens_python/recipe/multitenancy/asyncio/__init__.py
- supertokens_python/recipe/multitenancy/interfaces.py
- supertokens_python/recipe/multitenancy/recipe_implementation.py
- supertokens_python/recipe/multitenancy/syncio/__init__.py
Make config optional
-   https://github.com/supertokens/supertokens-python/pull/365
-   If no such branch …
> fix: Make config optional

- supertokens_python/recipe/userroles/asyncio/__init__.py
- supertokens_python/recipe/userroles/interfaces.py
- supertokens_python/recipe/userroles/recipe.py
- supertokens_python/recipe/userroles/recipe_implementation.py
- supertokens_python/recipe/userroles/syncio/__init__.py
User roles recipe multitenancy features
-   https://github.com/supertokens/supertokens-node/pull/600/
- …
> fix: Userroles recipe multitenancy features

- supertokens_python/recipe/userroles/asyncio/__init__.py
- supertokens_python/recipe/userroles/interfaces.py
- supertokens_python/recipe/userroles/recipe_implementation.py
Make tenant id compulsory in userroles
-   https://github.com/supertokens/supertokens-node/pull/605
- 
- …
> fix: Make tenant id compulsory in userroles

- tests/userroles/test_multitenancy.py
Add test for multitenant userroles
-   https://github.com/supertokens/supertokens-node/pull/600
-   If no …
> test: Add test for multitenant userroles

- supertokens_python/recipe/dashboard/api/userdetails/user_sessions_get.py
- supertokens_python/recipe/emailpassword/api/implementation.py
- supertokens_python/recipe/emailverification/recipe.py
- supertokens_python/recipe/passwordless/api/implementation.py
- supertokens_python/recipe/session/access_token.py
- supertokens_python/recipe/session/asyncio/__init__.py
- supertokens_python/recipe/session/interfaces.py
- supertokens_python/recipe/session/recipe.py
- supertokens_python/recipe/session/recipe_implementation.py
- supertokens_python/recipe/session/session_class.py
- supertokens_python/recipe/session/session_functions.py
- supertokens_python/recipe/session/session_request_functions.py
- supertokens_python/recipe/session/syncio/__init__.py
- supertokens_python/recipe/thirdparty/api/implementation.py
- tests/sessions/claims/test_create_new_session.py
- tests/sessions/test_access_token_v3.py
Session recipe multitenancy changes
- https://github.com/supertokens/supertokens-node/pull/607
-   If no …
> feat: Session recipe multitenancy changes

- supertokens_python/recipe/emailpassword/api/implementation.py
- supertokens_python/recipe/emailpassword/asyncio/__init__.py
- supertokens_python/recipe/emailpassword/interfaces.py
- supertokens_python/recipe/emailpassword/syncio/__init__.py
- supertokens_python/recipe/emailpassword/utils.py
- supertokens_python/recipe/thirdpartyemailpassword/asyncio/__init__.py
- supertokens_python/recipe/thirdpartyemailpassword/interfaces.py
- supertokens_python/recipe/thirdpartyemailpassword/syncio/__init__.py
- supertokens_python/recipe/thirdpartyemailpassword/types.py
Add reset password email functions
-   https://github.com/supertokens/supertokens-node/pull/626
-   If no …
> feat: Add reset password email functions

- supertokens_python/recipe/dashboard/api/userdetails/user_sessions_get.py
- supertokens_python/recipe/dashboard/recipe.py
- supertokens_python/recipe/dashboard/utils.py
Update dashboard recipe based on multitenancy
-   https://github.com/supertokens/supertokens-node/pull/631/ …
> fix: Update dashboard recipe based on multitenancy

- supertokens_python/recipe/emailpassword/asyncio/__init__.py
- supertokens_python/recipe/emailpassword/syncio/__init__.py
- supertokens_python/recipe/userroles/asyncio/__init__.py
- supertokens_python/recipe/userroles/syncio/__init__.py
- tests/emailpassword/test_multitenancy.py
- tests/thirdparty/test_multitenancy.py
- tests/userroles/test_multitenancy.py
Set tenant_id as None by default in ep and userroles functions
No related issue. This is important to have a good DX for python devs, keep them consistent with other recipes (and modify fewer tests related to these recipes)
-   To know which one it is, run find the latest released tag (`git tag`) in the format …
> fix: Set tenant_id as None by default in ep and userroles functions

- supertokens_python/recipe/emailpassword/utils.py
- supertokens_python/recipe/passwordless/recipe_implementation.py
- supertokens_python/recipe/thirdparty/api/implementation.py
- supertokens_python/recipe/thirdparty/provider.py
- supertokens_python/recipe/thirdparty/providers/config_utils.py
- supertokens_python/recipe/thirdparty/providers/custom.py
- supertokens_python/recipe/thirdparty/recipe_implementation.py
- supertokens_python/recipe/userroles/recipe.py
- tests/Django/test_django.py
- tests/Flask/test_flask.py
- tests/emailpassword/test_multitenancy.py
- tests/passwordless/test_mutlitenancy.py
- tests/sessions/claims/test_create_new_session.py
- tests/sessions/claims/test_get_claim_value.py
- tests/sessions/claims/test_primitive_array_claim.py
- tests/sessions/claims/test_primitive_claim.py
- tests/sessions/claims/test_set_claim_value.py
- tests/sessions/claims/test_validate_claims_for_session_handle.py
- tests/sessions/claims/utils.py
- tests/test_session.py
- tests/thirdparty/test_multitenancy.py
- tests/thirdparty/test_thirdparty.py
- tests/userroles/test_multitenancy.py
Fix failures in Multitenancy tests for all the recipes.
- …
> fix: Multitenancy tests for all the recipes

- supertokens_python/recipe/multitenancy/__init__.py
- supertokens_python/recipe/multitenancy/exceptions.py
- supertokens_python/recipe/multitenancy/recipe.py
- supertokens_python/recipe/multitenancy/utils.py
- supertokens_python/recipe/thirdparty/api/authorisation_url.py
- supertokens_python/recipe/thirdparty/api/signinup.py
- supertokens_python/recipe/thirdparty/interfaces.py
- supertokens_python/recipe/thirdparty/recipe_implementation.py
Remove error handlers from multitenancy recipe
-   https://github.com/supertokens/supertokens-node/pull/632/
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released …
> fix: Remove error handlers from multitenancy recipe

- supertokens_python/recipe/session/asyncio/__init__.py
- supertokens_python/recipe/session/interfaces.py
- supertokens_python/recipe/session/recipe_implementation.py
- supertokens_python/recipe/session/syncio/__init__.py
- supertokens_python/recipe/session/utils.py
- tests/sessions/claims/test_verify_session.py
Add tenant id in global claim validators
-   https://github.com/supertokens/supertokens-node/pull/634/files …
> fix: Add tenant id in global claim validators

- supertokens_python/recipe/multitenancy/recipe.py
allowed domain claim and some typos
-   https://github.com/supertokens/supertokens-node/pull/650/
-   If no …
> fix: allowed domain claim and some typos

- supertokens_python/recipe/dashboard/api/list_tenants.py
- supertokens_python/recipe/dashboard/interfaces.py
- supertokens_python/recipe/multitenancy/interfaces.py
- supertokens_python/recipe/multitenancy/recipe_implementation.py
Remove core config from dashboard tenants list response
-   https://github.com/supertokens/supertokens-node/pull/635/ …
> refactor: Remove core config from dashboard tenants list response

- supertokens_python/recipe/multitenancy/api/implementation.py
- supertokens_python/recipe/multitenancy/asyncio/__init__.py
- supertokens_python/recipe/multitenancy/interfaces.py
- supertokens_python/recipe/multitenancy/recipe.py
- supertokens_python/recipe/multitenancy/recipe_implementation.py
- supertokens_python/recipe/thirdparty/api/authorisation_url.py
- supertokens_python/recipe/thirdparty/api/signinup.py
- supertokens_python/recipe/thirdparty/interfaces.py
- supertokens_python/recipe/thirdparty/providers/config_utils.py
- supertokens_python/recipe/thirdparty/recipe_implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/interfaces.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/implementation.py
- supertokens_python/recipe/thirdpartyemailpassword/recipeimplementation/third_party_recipe_implementation.py
- supertokens_python/recipe/thirdpartypasswordless/interfaces.py
- supertokens_python/recipe/thirdpartypasswordless/recipeimplementation/implementation.py
- supertokens_python/recipe/thirdpartypasswordless/recipeimplementation/third_party_recipe_implementation.py
- tests/multitenancy/test_tenants_crud.py
- tests/thirdparty/test_multitenancy.py
handle tenant not found error
-   https://github.com/supertokens/supertokens-node/pull/639
-   If no such …
> fix: handle tenant not found error

- supertokens_python/recipe/dashboard/__init__.py
- supertokens_python/recipe/multitenancy/recipe_implementation.py
- supertokens_python/recipe/session/asyncio/__init__.py
- supertokens_python/recipe/session/syncio/__init__.py
- tests/auth-react/fastapi-server/app.py
- tests/auth-react/flask-server/app.py
- tests/thirdpartypasswordless/test_authorisation_url_feature.py
Linter and formatter failures
-   If no such branch exists, …
> fix: Linter and formatter failures

- CHANGELOG.md
- addDevTag
- setup.py
- supertokens_python/constants.py
- supertokens_python/querier.py
- tests/test_querier.py
Add 429 rate limting from SaaS for v0.12 …
> feat: Add 429 rate limting from SaaS for v0.12

- supertokens_python/querier.py
- tests/frontendIntegration/django2x/polls/urls.py
- tests/frontendIntegration/django2x/polls/views.py
- tests/frontendIntegration/django3x/polls/urls.py
- tests/frontendIntegration/django3x/polls/views.py
- tests/frontendIntegration/fastapi-server/app.py
- tests/frontendIntegration/flask-server/app.py
Fix failing CI tests for v0.12 patch release …
> fix: Failing CI tests for v0.12 patch release

- CHANGELOG.md
- supertokens_python/recipe/session/with_jwt/recipe_implementation.py
- supertokens_python/recipe/session/with_jwt/session_class.py
Fixes session recipe with jwt where the lifetime of the jwt is set to 1 in case it is < 1
-   https://github.com/supertokens/supertokens-node/pull/681/
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose …
> fix: JWT lifetime setting issue

- tests/auth-react/django3x/polls/urls.py
- tests/auth-react/django3x/polls/views.py
- tests/auth-react/fastapi-server/app.py
- tests/auth-react/flask-server/app.py
- tests/frontendIntegration/django2x/polls/urls.py
- tests/frontendIntegration/django2x/polls/views.py
- tests/frontendIntegration/django3x/polls/urls.py
- tests/frontendIntegration/django3x/polls/views.py
- tests/frontendIntegration/fastapi-server/app.py
- tests/frontendIntegration/flask-server/app.py
Fix failing tests in the CI
-   If no such branch exists, then create one from the latest released branch. …
> fix: Failing tests in the CI

- tests/frontendIntegration/django2x/polls/views.py
Fix failing django2x website tests
-   [ ] Issue …
> fix: Failing django2x website tests

- CHANGELOG.md
- addDevTag
- setup.py
- supertokens_python/constants.py
- supertokens_python/querier.py
- tests/test_querier.py
- tests/utils.py
Add 429 rate limting from SaaS for v0.11 …
> feat: Add 429 rate limting from SaaS for v0.11

- CHANGELOG.md
- addDevTag
- setup.py
- supertokens_python/constants.py
- supertokens_python/querier.py
- tests/test_querier.py
- tests/utils.py
Add 429 rate limting from SaaS for v0.10 …
> feat: Add 429 rate limting from SaaS for v0.10

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/session/asyncio/__init__.py
- supertokens_python/recipe/session/constants.py
- supertokens_python/recipe/session/recipe_implementation.py
- supertokens_python/recipe/session/session_request_functions.py
- tests/sessions/test_access_token_version.py
Ignore protected props in `create_new_session` functions
- https://github.com/supertokens/supertokens-node/pull/690 …
> fix: ignore protected props in create_new_session functions

- CHANGELOG.md
Mention SDK and core versions compatible after migrating to `v0.15` 
-   If no such branch exists, then …
> chores: Mention SDK and core versions compatible after 0.15 migration

- .circleci/config_continue.yml
- CHANGELOG.md
- setup.py
- supertokens_python/__init__.py
- supertokens_python/async_to_sync_wrapper.py
- supertokens_python/constants.py
- supertokens_python/querier.py
- supertokens_python/supertokens.py
- supertokens_python/utils.py
- tests/test_config.py
Use nest-asyncio when configured with env var …
> feat: Use nest-asyncio when configured with env var

- CHANGELOG.md
- supertokens_python/recipe/thirdparty/api/implementation.py
- supertokens_python/recipe/thirdparty/provider.py
- supertokens_python/recipe/thirdparty/providers/config_utils.py
- supertokens_python/recipe/thirdparty/providers/custom.py
- supertokens_python/recipe/thirdparty/providers/twitter.py
Add Twitter provider
- https://github.com/supertokens/supertokens-node/pull/694
-   If no such branch …
> feat: Add Twitter provider

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- Relaxed constraint on `pyJWT` dependency.
- This is done because some users face `InvalidSignatureError` when decoding the access token with the latest `pyJWT` version.
-   #445 
Difficult to reproduce the issue, but all the existing tests work, so the change is safe to make.
-   To know which one it is, run …
> Relax `pyJWT` dependency constraint to `2.5.0`

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/thirdparty/api/signinup.py
- tests/thirdparty/test_thirdparty.py
Fixed server error when the sign in up API was called using oAuthTokens without passing the `redirect_uri_info`.
Added unit test
-   To know which one it is, …
> fix: server error when `redirect_uri_info` is not passed in the sign_in_up API

- CHANGELOG.md
- setup.py
- supertokens_python/__init__.py
- supertokens_python/constants.py
- supertokens_python/logger.py
- supertokens_python/supertokens.py
- tests/test_logger.py
Added debug flag in the SuperTokenConfig in the init() for logging
Added unit tests.
-   To know which one it …
> feat: added debug flag in the SuperTokenConfig in the init() for logging

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/thirdparty/providers/linkedin.py
This PR updates the LinkedIn OAuth implementation as per the [recent changes.](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2?context=linkedin%2Fconsumer%2Fcontext#authenticating-members)
Tested manually
-   To know which one it is, run find the latest …
> fix: LinkedIn OAuth

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/framework/django/django_request.py
- tests/Django/test_django.py
`get_raw_uri` method was removed from [Django v4](https://django.readthedocs.io/en/stable/releases/4.0.html) but our SDK was still using it. I have replaced that method by `build_absolute_uri` as suggested in the changelog.  
Delete User API was breaking on user dashboard because of this issue. I tested it manually after doing this change.
-   [ ] Issue this PR against the …
> fix: Incompatibility with django 4.0 and higher

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/dashboard/api/implementation.py
- tests/dashboard/test_dashboard.py
- tests/utils.py
This PR replicates the changes done in the https://github.com/supertokens/supertokens-node/pull/760 PR.
-   https://github.com/supertokens/supertokens-node/pull/760
-   [x] Changes to the version if …
> fix: normalise connection_uri in the dashboard recipe

- CHANGELOG.md
- dev-requirements.txt
- setup.py
- supertokens_python/constants.py
- supertokens_python/ingredients/emaildelivery/services/smtp.py
This PR relaxes constraint on `aiosmtplib` library. 
- https://github.com/supertokens/supertokens-python/issues/481
-   In …
> fix: relax constraint on aiosmtplib lib

- CHANGELOG.md
- supertokens_python/framework/fastapi/fastapi_middleware.py
-   https://github.com/supertokens/supertokens-python/issues/470
-   [ …
> fix: changelog and fastapi middleware

- tests/frontendIntegration/drf_async/polls/views.py
- tests/frontendIntegration/drf_sync/polls/views.py
> fix: drf fix

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/thirdparty/api/implementation.py
- tests/thirdparty/test_thirdparty.py
-   https://github.com/supertokens/supertokens-python/issues/498
- Added test
-   To know which one it is, run find the latest …
> fix: generate_fake_email param ordering

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/framework/fastapi/fastapi_middleware.py
-   https://github.com/supertokens/supertokens-python/issues/503
-   [ …
> fix: better fastapi middleware

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/querier.py
- supertokens_python/supertokens.py
- supertokens_python/utils.py
- tests/test_querier.py
Adds caching to querier so that core calls are reduced. The cache is invalidated anytime a non GET API call is made.
Lots of tests
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than …
> adds caching for querier

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/session/session_request_functions.py
- tests/sessions/test_auth_mode.py
test: move the session object and claims to the BE sdk server
-   In …
> test: move the session object and claims to the BE sdk server

- CHANGELOG.md
- supertokens_python/recipe/jwt/recipe_implementation.py
- supertokens_python/recipe/session/__init__.py
- supertokens_python/recipe/session/access_token.py
- supertokens_python/recipe/session/constants.py
- supertokens_python/recipe/session/jwks.py
- supertokens_python/recipe/session/recipe.py
- supertokens_python/recipe/session/session_functions.py
- supertokens_python/recipe/session/utils.py
- tests/sessions/test_access_token_version.py
- tests/sessions/test_jwks.py
> fix: configurable jwk cache duration

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/querier.py
- supertokens_python/recipe/dashboard/api/analytics.py
- supertokens_python/recipe/emailpassword/emaildelivery/services/backward_compatibility/__init__.py
- supertokens_python/recipe/emailverification/emaildelivery/services/backward_compatibility/__init__.py
- supertokens_python/recipe/passwordless/emaildelivery/services/backward_compatibility/__init__.py
- supertokens_python/recipe/passwordless/smsdelivery/services/backward_compatibility/__init__.py
- supertokens_python/recipe/passwordless/smsdelivery/services/supertokens/__init__.py
- supertokens_python/recipe/thirdparty/providers/custom.py
- supertokens_python/recipe/thirdparty/providers/utils.py
-   https://github.com/supertokens/supertokens-python/issues/516
-   [ …
> fix: timeout

- tests/test_middleware.py
This PR fixes some tests that were failing due to the form validation related changes.
No issues
Middleware test cases should pass.
-   To know which one it …
> Fix failing tests related to middleware because of form validation

- .github/workflows/pre-commit-hook-run.yml
- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/emailpassword/api/utils.py
- supertokens_python/recipe/emailpassword/types.py
- supertokens_python/recipe/emailpassword/utils.py
- tests/emailpassword/test_passwordreset.py
- tests/emailpassword/test_signin.py
- tests/emailpassword/test_signup.py
Port for form validation changes to support any type of value in form fields instead of just strings.
Reference PR: https://github.com/supertokens/supertokens-node/pull/924
> PS: This also includes some fixes for the pre-commit hook workflow that was failing to run earlier.
All tests in authFlow, passwordReset should pass
-   In …
> fix: Add support for any type in value field instead of only string

- tests/emailpassword/test_passwordreset.py
- tests/input_validation/test_input_validation.py
fixes issues with some tests that were failing after adding support for any type of field values in formFields
[Failing tests](https://app.circleci.com/pipelines/github/supertokens/supertokens-python/3261/workflows/4115b3cf-2263-441c-a1e8-3380406b78be/jobs/4773)
- `test_init_validation_emailpassword` should pass
- `test_email_validation_checks_in_generate_token_API` should pass
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if …
> fix: Failing tests regarding any type support in formFields

- CHANGELOG.md
This PR updates the changelog to add details of the form field type change
-   To know which one it is, run find the latest released tag (`git tag`) in the …
> fix: Update changelog with migration guide for form field value consumption

- .circleci/config_continue.yml
- .circleci/setupAndTestWithFrontend.sh
- .circleci/setupAndTestWithFrontendWithDjango.sh
- .circleci/setupAndTestWithFrontendWithDjango2x.sh
- .circleci/setupAndTestWithFrontendWithDrfAsync.sh
- .circleci/setupAndTestWithFrontendWithDrfSync.sh
- .circleci/setupAndTestWithFrontendWithFlask.sh
- .circleci/websiteDjango.sh
- .circleci/websiteDjango2x.sh
- .circleci/websiteDrfAsync.sh
- .circleci/websiteDrfSync.sh
- .circleci/websiteFastApi.sh
- .circleci/websiteFlask.sh
- CHANGELOG.md
- supertokens_python/recipe/thirdparty/types.py
- supertokens_python/types.py
- supertokens_python/utils.py
- tests/auth-react/django3x/mysite/utils.py
- tests/auth-react/fastapi-server/app.py
- tests/auth-react/flask-server/app.py
- tests/utils.py
> fix: changelog and tests

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/dashboard/api/userdetails/user_put.py
- supertokens_python/recipe/dashboard/constants.py
- supertokens_python/recipe/dashboard/recipe.py
- supertokens_python/recipe/multitenancy/interfaces.py
- supertokens_python/types.py
> fix: dashboard / type fixes

- supertokens_python/recipe/dashboard/api/multitenancy/get_third_party_config.py
> fix: lint fix

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/framework/django/django_response.py
- tests/Django/test_django.py
- tests/test_logger.py
- tests/test_session.py
- tests/thirdparty/test_thirdparty.py
- tests/utils.py
- Makes timestamps consistent, uses UTC timezone
- #554
- Run supertokens-python test suite
-   To know which one it is, run find the latest released tag …
> update: uses UTC for timestamps

- CHANGELOG.md
- dev-requirements.txt
- setup.py
- supertokens_python/constants.py
- tests/test_querier.py
- Pins `httpx`/`respx` to current major versions (<1.0.0)
- Will allow users to update their dependencies without us having to keep up
- Fixes broken tests due to latest `httpx` changes
- Removes `respx` dependency from `fastapi` install
- `fastapi` has no dependency on `respx`
- We only use `respx` in tests
- Bump version to `0.28.1`
-   [ ] …
> build: bump `httpx`/`respx` dependencies

- .circleci/config_continue.yml
- .github/workflows/pre-commit-hook-run.yml
- CHANGELOG.md
- Fixes issues with `setuptools` and `setuptools-scm` versions
```
ERROR: setuptools==56.0.0 is used in combination with setuptools-scm>=8.x
Your build configuration is incomplete and previously worked by accident!
setuptools-scm requires setuptools>=61
``` …
> build: upgrade `pip`/`setuptools` in CI

- .gitignore
- CHANGELOG.md
- dev-requirements.txt
- setup.py
- supertokens_python/env/base.py
- supertokens_python/env/utils.py
- supertokens_python/utils.py
- tests/test_utils.py
- tests/utils.py
- Workaround till tldextract#233 is implemented
- Adds flag to control disabling HTTP requests
- Adds `pyfakefs` to use in tests
- closes #562 …
> feat: allow disabling `tldextract` HTTP requests

- CHANGELOG.md
- supertokens_python/normalised_url_path.py
- tests/test_config.py
- tests/utils.py
- Makes URL path normalization case sensitive
- Updates `normalise_url_path_or_throw_error` to be case sensitive
- URL paths will not be converted to lower-case, and will be kept as-is.
- #537
-   [x] …
> fix: makes url path normalization case sensitive

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/recipe/totp/api/remove_device.py
- tests/test-server/test_functions_mapper.py
- Fixes an issue where `removeDevice` API allowed removing TOTP devices without the user completing MFA.
- https://github.com/supertokens/supertokens-node/pull/962
-   [ ] Changes to the version if …
> fix: validate MFA claim before allowing TOTP device removal

- CHANGELOG.md
- supertokens_python/recipe/dashboard/api/multitenancy/get_third_party_config.py
- Fixes issue with ThirdParty provider info on dashboard
- https://github.com/supertokens/supertokens-node/pull/989
-   In …
> fix: thirdparty info for dashboard

- CHANGELOG.md
- supertokens_python/recipe/totp/api/implementation.py
- supertokens_python/recipe/totp/api/remove_device.py
- Ensures that verified TOTP devices can only be removed after MFA requirements are completed
- Removes override for global claim validators
- https://github.com/supertokens/supertokens-node/commit/28a0f4adf4a9040e9ee0b3d2f3c571064b877625
- Updates handling introduced in #579 
-   [ …
> fix: check for MFA claim in removeDevice

- .github/workflows/backend-sdk-testing.yml
- CHANGELOG.md
- compose.yml
- tests/test-server/app.py
- Sets up workflow to run backend-sdk-testing tests
- Updates test-servers to work with updated tests
-   In …
> ci: backend-sdk-testing

- CHANGELOG.md
- setup.py
- supertokens_python/constants.py
- supertokens_python/framework/django/django_response.py
- tests/Django/test_django.py
- tests/test_session.py
- tests/utils.py
- Fixes cookies being set without expiry in Django
- Reverts timezone change from 0.28.0 and uses GMT
- #586
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Date#gmt
-   [x] …
> fix: reverts cookie timezones to GMT

- .github/workflows/auth-react-test-1-django.yml
- .github/workflows/auth-react-test-1-fastapi.yml
- .github/workflows/auth-react-test-1-flask.yml
- .github/workflows/auth-react-test-2.yml
- .github/workflows/auth-react-test-3.yml
- .github/workflows/backend-sdk-testing.yml
- .github/workflows/lint-code.yml
- .github/workflows/lint-pr.yml
- .github/workflows/pipeline-dev-tag.yml
- .github/workflows/pipeline-release-tag.yml
- .github/workflows/unit-test.yml
- .github/workflows/website-test.yml
- hooks/populate-hook-constants.sh
> feat: dev and release pipelines

- tests/test-server/app.py
- tests/test-server/session.py
- Adds support for token transfer method
- Adds route for `createNewSession`
- supertokens/backend-sdk-testing#62
-   In …
> test: setting session cookies
